-- MySQL Script generated by MySQL Workbench
-- Fri 12 Apr 2024 04:46:04 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `MovieBookingSystem`;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MovieBookingSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

CREATE TABLE IF NOT EXISTS `Role` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UserStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserStatus` ;

CREATE TABLE IF NOT EXISTS `UserStatus` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `id` INT NOT NULL,
  `account_id` INT NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_account_id_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_user_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_user_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_status`
    FOREIGN KEY (`status`)
    REFERENCES `UserStatus` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `id` INT NOT NULL,
  `role` INT NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `phone_number` VARCHAR(16) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  INDEX `fk_account_role_idx` (`role` ASC) VISIBLE,
  INDEX `fk_account_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_role`
    FOREIGN KEY (`role`)
    REFERENCES `Role` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `pay_rate` INT NOT NULL,
  `permissions` BINARY(4) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_employee_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_employee_account_Id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_account_Id`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `pay_rate` INT NOT NULL,
  `permissions` BINARY(4) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_admin_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_admin_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Language` ;

CREATE TABLE IF NOT EXISTS `Language` (
  `id` INT NOT NULL,
  `language_name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `language_name_UNIQUE` (`language_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Dubbing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dubbing` ;

CREATE TABLE IF NOT EXISTS `Dubbing` (
  `id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_dubbing_language_id`
    FOREIGN KEY (`id`)
    REFERENCES `Language` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FilmRating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FilmRating` ;

CREATE TABLE IF NOT EXISTS `FilmRating` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Guest` ;

CREATE TABLE IF NOT EXISTS `Guest` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guest_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_guest_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Member` ;

CREATE TABLE IF NOT EXISTS `Member` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `points` INT NOT NULL DEFAULT '0',
  `discount` INT NOT NULL DEFAULT '0',
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_member_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movie` ;

CREATE TABLE IF NOT EXISTS `Movie` (
  `id` INT NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(2048) NULL DEFAULT NULL,
  `film_rating` INT NULL DEFAULT NULL,
  `duration` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `fk_language_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_film_rating_id_idx` (`film_rating` ASC) VISIBLE,
  CONSTRAINT `fk_movie_film_rating_id`
    FOREIGN KEY (`film_rating`)
    REFERENCES `FilmRating` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movie_language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `Language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PaymentInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaymentInformation` ;

CREATE TABLE IF NOT EXISTS `PaymentInformation` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `address` VARCHAR(256) NOT NULL,
  `city` VARCHAR(256) NOT NULL,
  `state` VARCHAR(256) NOT NULL,
  `zip` INT NOT NULL,
  `cvv` INT NOT NULL,
  `card_number` INT NOT NULL,
  `expiry` DATE NOT NULL,
  `first_name` VARCHAR(256) NOT NULL,
  `last_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_information_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Resolution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Resolution` ;

CREATE TABLE IF NOT EXISTS `Resolution` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sale` ;

CREATE TABLE IF NOT EXISTS `Sale` (
  `id` INT NOT NULL,
  `discount` INT NOT NULL COMMENT 'Discount as a percentage. It is stored as an int for precision purposes.',
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SeatType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SeatType` ;

CREATE TABLE IF NOT EXISTS `SeatType` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TheatreRoom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheatreRoom` ;

CREATE TABLE IF NOT EXISTS `TheatreRoom` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `num_seats` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Seat` ;

CREATE TABLE IF NOT EXISTS `Seat` (
  `id` INT NOT NULL,
  `theatre_id` INT NOT NULL,
  `is_occupied` TINYINT NOT NULL,
  `seat_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_theatre_id_idx` (`theatre_id` ASC) VISIBLE,
  INDEX `fk_seat_seat_type_id_idx` (`seat_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_seat_type_id`
    FOREIGN KEY (`seat_type_id`)
    REFERENCES `SeatType` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seat_theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `TheatreRoom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SoundSystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SoundSystem` ;

CREATE TABLE IF NOT EXISTS `SoundSystem` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Subtitle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subtitle` ;

CREATE TABLE IF NOT EXISTS `Subtitle` (
  `id` INT NOT NULL,
  `language_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subtitle_language_id_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `fk_subtitle_language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `Language` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Showing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Showing` ;

CREATE TABLE IF NOT EXISTS `Showing` (
  `id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `resolution_id` INT NULL DEFAULT NULL,
  `subtitle_id` INT NULL DEFAULT NULL,
  `dubbing_id` INT NULL DEFAULT NULL,
  `sound_type_id` INT NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL COMMENT 'Status will say SHOWING or NOT SHOWING',
  `theatre_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `fk_resolution_id_idx` (`resolution_id` ASC) VISIBLE,
  INDEX `fk_subtitle_id_idx` (`subtitle_id` ASC) VISIBLE,
  INDEX `fk_dubbing_id_idx` (`dubbing_id` ASC) VISIBLE,
  INDEX `fk_sound_type_id_idx` (`sound_type_id` ASC) VISIBLE,
  INDEX `fk_theatre_id_idx` (`theatre_id` ASC) VISIBLE,
  CONSTRAINT `fk_showing_dubbing_id`
    FOREIGN KEY (`dubbing_id`)
    REFERENCES `Dubbing` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_showing_movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `Movie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_showing_resolution_id`
    FOREIGN KEY (`resolution_id`)
    REFERENCES `Resolution` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_showing_sound_type_id`
    FOREIGN KEY (`sound_type_id`)
    REFERENCES `SoundSystem` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_showing_subtitle_id`
    FOREIGN KEY (`subtitle_id`)
    REFERENCES `Subtitle` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TicketStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TicketStatus` ;

CREATE TABLE IF NOT EXISTS `TicketStatus` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TicketType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TicketType` ;

CREATE TABLE IF NOT EXISTS `TicketType` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `suggested_price` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ticket` ;

CREATE TABLE IF NOT EXISTS `Ticket` (
  `id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `showing_time` INT NOT NULL,
  `price` INT NOT NULL,
  `seat_id` INT NOT NULL,
  `theatre_id` INT NOT NULL,
  `status` INT NOT NULL,
  `ticket_type` INT NOT NULL,
  `bought_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `fk_showing_time_id_idx` (`showing_time` ASC) VISIBLE,
  INDEX `fk_seat_id_idx` (`seat_id` ASC) VISIBLE,
  INDEX `fk_theatre_id_idx` (`theatre_id` ASC) VISIBLE,
  INDEX `fk_status_idx` (`status` ASC) VISIBLE,
  INDEX `fk_ticket_type_id_idx` (`ticket_type` ASC) VISIBLE,
  INDEX `fk_bought_by_idx` (`bought_by` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_bought_by`
    FOREIGN KEY (`bought_by`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `Movie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_seat_id`
    FOREIGN KEY (`seat_id`)
    REFERENCES `Seat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_showing_time_id`
    FOREIGN KEY (`showing_time`)
    REFERENCES `Showing` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_status_id`
    FOREIGN KEY (`status`)
    REFERENCES `TicketStatus` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_theatre_id`
    FOREIGN KEY (`theatre_id`)
    REFERENCES `TheatreRoom` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_ticket_type_id`
    FOREIGN KEY (`ticket_type`)
    REFERENCES `TicketType` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
